/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package MAVLink.enums;

/**
 * Enumeration of distance sensor types
 */
public class SCENARIO_CMD_ENUM {
   public static final int SCENARIO_CMD_SET_START_TIME = 0; /* set start time for scenario  (param1: start_time) | */
   public static final int SCENARIO_CMD_STOP_SCENARIO = 1; /* stop scenario | */
   public static final int SCENARIO_CMD_EMERGENCY_LAND = 2; /* land | */
   public static final int SCENARIO_CMD_SET_CONFIGS = 3; /* set vairous configurations param1: base vehicle pos x, param2: base vehicle pos y, param5: scenario file name | */
   public static final int SCENARIO_CMD_RESET_CONFIGS = 4; /* reset configurations | */
   public static final int SCENARIO_CMD_ENUM_ENUM_END = 5; /*  | */
}
            